name: Convert ONNX RealESRGAN Anime to CoreML

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coremltools==3.2 onnx

      - name: Convert to CoreML
        run: |
          python convert_to_coreml.py models/RealESRGAN_x4plus_anime.onnx RealESRGAN_x4plus_anime.mlmodel

      - name: Upload CoreML model
        uses: actions/upload-artifact@v4
        with:
          name: RealESRGAN_x4plus_anime-mlmodel
          path: RealESRGAN_x4plus_anime.mlmodel
